---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app-argocd
  template:
    metadata:
      labels:
        app: simple-app-argocd
    spec:
      containers:
      - name: nginx
        image: docker.io/karydock/k8s-web-hello:2.0.0
        imagePullPolicy: Always
        
        ports:
        - containerPort: 3000
