apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: LoadBalancer
  selector:
    app: simple-app-argocd
  ports:
      - targetPort: 3000
        protocol: TCP
        port: 8080
